// Embeds src/studio/page.html into the Worker bundle as a string module.
// Run after editing page.html: `npm run studio:build`. The test suite fails if
// page.generated.ts is out of date, so a stale embed cannot be deployed unnoticed.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const dir = fileURLToPath(new URL("../src/studio/", import.meta.url));
const html = readFileSync(dir + "page.html", "utf8");
const out =
    "// GENERATED by scripts/build-studio.mjs from page.html. Do not edit; run `npm run studio:build`.\n" +
    `export const STUDIO_HTML: string = ${JSON.stringify(html)};\n`;
if (process.argv.includes("--check")) {
    const cur = readFileSync(dir + "page.generated.ts", "utf8");
    if (cur !== out) {
        console.error("page.generated.ts is stale; run npm run studio:build");
        process.exit(1);
    }
} else {
    writeFileSync(dir + "page.generated.ts", out);
    console.log(`wrote page.generated.ts (${html.length} chars)`);
}
